import React, { useEffect, useState } from 'react';
import { Search, RefreshCw } from 'lucide-react';
import { ColumnDef } from '@tanstack/react-table';
import { useUsers, useUserDetail } from '../hooks/queries';
import { UserRow } from '../types';
import { DataTable } from '../components/DataTable';
import { Avatar, Badge, Button, Dialog, Tabs } from '../components/ui';

type DetailRecord = Record<string, unknown>;
type DetailKey = 'holdings' | 'watchlist' | 'transactions' | 'feedback';
const detailTabs: Array<{ key: DetailKey; label: string; columns: Array<{ key: string; header: string }> }> = [
  { key: 'holdings', label: '持仓', columns: [{ key: 'fund_name', header: '基金名称' }, { key: 'fund_code', header: '代码' }, { key: 'current_value', header: '当前市值' }, { key: 'hold_profit', header: '持有收益' }, { key: 'hold_profit_rate', header: '收益率' }, { key: 'shares', header: '份额' }, { key: 'updated_at', header: '更新时间' }] },
  { key: 'watchlist', label: '自选', columns: [{ key: 'fund_name', header: '基金名称' }, { key: 'fund_code', header: '代码' }, { key: 'fund_type', header: '类型' }, { key: 'created_at', header: '添加时间' }] },
  { key: 'transactions', label: '交易流水', columns: [{ key: 'fund_code', header: '代码' }, { key: 'transaction_type', header: '类型' }, { key: 'trade_date', header: '交易日' }, { key: 'amount', header: '金额' }, { key: 'shares', header: '份额' }, { key: 'nav', header: '净值' }, { key: 'remark', header: '备注' }, { key: 'is_buy_point', header: 'B点' }] },
  { key: 'feedback', label: '反馈', columns: [{ key: 'category', header: '分类' }, { key: 'content', header: '内容' }, { key: 'status', header: '状态' }, { key: 'priority', header: '优先级' }, { key: 'created_at', header: '提交时间' }] },
];

function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '-'; }
function formatValue(value: unknown) { if (value === undefined || value === null || value === '') return '-'; const n = Number(value); return Number.isNaN(n) ? String(value) : new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 2 }).format(n); }

export default function UsersPage() {
  const [keyword, setKeyword] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [selectedUser, setSelectedUser] = useState<UserRow | null>(null); const [detailTab, setDetailTab] = useState<DetailKey>('holdings');
  const { data, isLoading, isError, error, refetch, isFetching } = useUsers(query, page, pageSize); const { data: detailData, isLoading: isDetailLoading } = useUserDetail(selectedUser?.openid || null); const total = data?.total || 0;
  useEffect(() => { if (total > 0 && page > Math.ceil(total / pageSize)) setPage(1); }, [page, pageSize, total]);
  const active = detailTabs.find((item) => item.key === detailTab) || detailTabs[0]; const rows = (detailData as Partial<Record<DetailKey, DetailRecord[]>> | undefined)?.[active.key] || [];
  const columns: ColumnDef<UserRow>[] = [{ header: '用户', accessorKey: 'nickname', cell: ({ row }) => { const user = row.original; const name = user.nickname || '微信用户'; return <button onClick={() => setSelectedUser(user)} className="flex min-w-0 items-center gap-2.5 bg-transparent p-0 text-left"><Avatar src={user.avatarUrl || user.avatar_url}>{name.slice(0, 1)}</Avatar><span className="truncate font-semibold text-primary hover:underline">{name}</span></button>; } }, { header: 'openid', accessorKey: 'openid', cell: ({ getValue }) => <code className="select-all text-xs">{getValue() as string}</code> }, { header: '持仓', accessorKey: 'holdingsCount' }, { header: '自选', accessorKey: 'watchlistCount' }, { header: '反馈', accessorKey: 'feedbackCount' }, { header: '注册时间', accessorFn: (row) => row.createdAt || row.created_at, cell: ({ getValue }) => formatDate(getValue() as string | undefined) }];
  function submitSearch(event: React.FormEvent) { event.preventDefault(); setQuery(keyword.trim()); setPage(1); setSelectedUser(null); }
  return <div className="flex flex-col gap-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-textMain">用户管理</h2><p className="mt-1 text-xs text-textMuted">按 openid 或昵称定位用户</p></div><Button variant="outline" className="h-10 w-10 px-0" onClick={() => refetch()} disabled={isLoading || isFetching} aria-label="刷新用户列表"><RefreshCw size={17} className={isFetching ? 'animate-spin' : ''} /></Button></div>
    <form onSubmit={submitSearch} className="flex max-w-2xl gap-3"><div className="flex h-10 flex-1 items-center gap-2 rounded-md border border-borderBase bg-white px-3 shadow-sm focus-within:border-primary focus-within:ring-3 focus-within:ring-primary/15"><Search size={17} className="text-textMuted" /><input className="w-full bg-transparent text-sm outline-none" placeholder="搜索 openid / 昵称" value={keyword} onChange={(event) => setKeyword(event.target.value)} /></div><Button className="h-10 min-w-20">搜索</Button></form>
    {isError && <div className="rounded-md border border-red-200 bg-red-50 p-4 text-xs text-red-600">加载用户列表失败：{error?.message || '未知错误'}</div>}
    <div><DataTable className="users-table" columns={columns} data={data?.items || []} loading={isLoading || isFetching} /><div className="flex flex-wrap items-center justify-between gap-3 rounded-b-xl border-x border-b border-borderBase bg-white px-4 py-3 text-sm text-textMuted"><span>{total ? `${(page - 1) * pageSize + 1}-${Math.min(page * pageSize, total)} / ${total}` : '暂无数据'}</span><div className="flex items-center gap-2"><select className="h-10 rounded-md border border-borderBase bg-white px-2" value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option value="10">10 / 页</option><option value="20">20 / 页</option><option value="50">50 / 页</option><option value="100">100 / 页</option></select><Button variant="outline" className="h-10" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>上一页</Button><Button variant="outline" className="h-10" disabled={page >= Math.ceil(total / pageSize)} onClick={() => setPage((p) => p + 1)}>下一页</Button></div></div></div>
    <Dialog open={!!selectedUser} onClose={() => { setSelectedUser(null); setDetailTab('holdings'); }} className="max-w-6xl"><div className="border-b border-borderBase px-6 py-5"><div className="flex items-center gap-3"><Avatar src={selectedUser?.avatarUrl || selectedUser?.avatar_url} className="h-11 w-11">{(selectedUser?.nickname || '微').slice(0, 1)}</Avatar><div><h3 className="font-bold text-textMain">{selectedUser?.nickname || '微信用户'}</h3><div className="mt-1 flex flex-wrap gap-3 text-xs text-textMuted"><code>{selectedUser?.openid}</code><span>注册时间 {formatDate(selectedUser?.createdAt || selectedUser?.created_at)}</span></div></div></div></div><Tabs items={detailTabs.map((item) => ({ value: item.key, label: `${item.label} ${(detailData as Partial<Record<DetailKey, DetailRecord[]>> | undefined)?.[item.key]?.length || 0}` }))} value={detailTab} onChange={(value) => setDetailTab(value as DetailKey)} />{isDetailLoading ? <div className="flex justify-center py-16 text-sm text-textMuted">加载用户详情...</div> : <div className="max-h-[62vh] overflow-auto"><table className="min-w-[860px] w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-xs text-textMuted"><tr>{active.columns.map((column) => <th key={column.key} className="whitespace-nowrap border-b border-borderBase px-4 py-3 text-left">{column.header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={String(row.id || index)} className="border-b border-slate-100"><>{active.columns.map((column) => <td key={column.key} className="max-w-[360px] px-4 py-3 text-textMain">{column.key === 'is_buy_point' ? <Badge variant="default">{row[column.key] ? '是' : '否'}</Badge> : column.key.endsWith('_at') ? formatDate(row[column.key] as string) : formatValue(row[column.key])}</td>)}</></tr>) : <tr><td colSpan={active.columns.length} className="py-14 text-center text-textMuted">暂无{active.label}数据</td></tr>}</tbody></table></div>}</Dialog></div>;
}
